### PR TITLE
Fix compatibility with glue v0.11

### PR DESCRIPTION
**Pull request by astrofrog**
This is still very much a work in progress, but I'll update this soon with some questions :)

### CODE REVIEW

**Comment by astrofrog** [comment]
@ejeschke - this is now ready, do you have any objections to me merging this?

**Comment by ejeschke** [comment]
@astrofrog, thanks for the work on this!  Let me give it a good tryout.  I'll report back soon.

**Comment by ejeschke** [comment]
This seems to work fine. The only issues are that the colorbar and cursor readout areas are not displayed properly:

glue-ginga-viewer

This could be an issue with how things are rendering on my 4K Linux display.  I didn't check it yet on Mac OS X.  But I think these can be tweaked by a later commit to just change the font size and requested size for those parts of the viewer.

So I think we can go ahead and merge.  After that I'll take a look at fixing those issues.

**Comment by astrofrog** [comment]
@ejeschke - thanks for checking this out! Things seem to work ok for me on Mac:

screen shot 2017-08-25 at 08 51 35

So it might indeed be easier if you try and fix this in a separate PR.

**Comment by ejeschke** [comment]
> Things seem to work ok for me on Mac

Good to know--that does look reasonable.  Hi-Res displays are not handled as nicely on Linux yet, so maybe it is just my setup.  I'll take a look at it and address with a separate PR if needed. Tnx.

**Comment by astrofrog** [comment]
@ejeschke - sounds good! It would be good to get a release out of the plugin and I can add it to the glueviz ginga channel, so either once you've had a look at this issue, or before if you plan to look at it in future, could you make a new major release? (v0.2?)

**Comment by ejeschke** [comment]
> could you make a new major release? (v0.2?)

I was thinking that myself. I'll take a quick look at it this next week and make a release one way or the other.

**Comment by astrofrog** [comment]
Perfect, thanks!

**Comment by pllim** [comment]
A bit late to this... Why did you remove `client.py`? I thought it was needed for Glue plugin in Ginga, is that not the case anymore? Did you test the Glue plugin?

**Comment by astrofrog** [comment]
@pllim - it's no longer needed - the way viewers are implemented now is without a client class. I'm planning on writing some docs describing the current architecture.

**Comment by pllim** [comment]
@astrofrog , I only saw the screenshots above for Ginga viewer in Glue. Did you test the Glue plugin in Ginga?

**Comment by astrofrog** [comment]
@pllim - no, but I assumed that hadn't changed with glue v0.11. Can you double check?

**Pull request merged**
