### PR TITLE
WIP: Fix Ginga viewer in Glue

### PR DESCRIPTION
**Pull request by pllim**
Thanks, Tom!

### CODE REVIEW

**Comment by pllim** [comment]
@astrofrog , here is the test log when I run the tests on this branch locally with dev Ginga and stable Glue.

[testlog.txt](https://github.com/ejeschke/glue-ginga/files/3463011/testlog.txt)

**Comment by ejeschke** [comment]
@pllim, @astrofrog, you might want to take a look at #33.  Sorry I didn't push this sooner; I had been meaning to get around to it a couple weeks ago.  It was working with a slightly earlier version of Glue with a simple update to Glue that I have [here](https://github.com/glue-viz/glue/pull/2058).  Unfortunately, I waited too long to submit that fix as a PR and Glue logic in the `_slice()` method has become a lot more complicated recently.

**Comment by pllim** [comment]
Thanks, @ejeschke ! This PR also fixes the Glue plugin in Ginga (sorry, the title is misleading). I'll have a look next week and see if I can combine our efforts into one.

**Comment by astrofrog** [comment]
(I've removed myself as a reviewer for now since this PR isn't ready)

**Comment by pllim** [comment]
We ended up not using this feature.

**Pull request closed without merging**
