### PR TITLE
Added dev version tagging using git hash

### LINKED ISSUE #7: Apply astropy package template?
What do you think, @astrofrog ?

### PR DESCRIPTION
**Pull request by pllim**
Added dev version tagging using git hash by copying over relevant codes from `astropy-helpers`. Closes #7.

### CODE REVIEW

**Comment by pllim** [comment]
If you don't think this clutters up `setup.py` too much, feel free to merge. This will change `0.1.dev0` to something more meaningful like `0.1.dev19`.

**Comment by ejeschke** [comment]
@pllim, is this basically pulled from the `astropy-helpers` template?

**Comment by ejeschke** [comment]
Sorry, I just now saw your comment that it is.  Looks fine.  Feel free to merge.

**Comment by pllim** [comment]
Was trying to see the Travis results but they are going incredibly slow. Since all but one have passed (that one still running), I am just going to merge.

**Pull request merged**
